### ISSUE TITLE
ImportError: cannot import name 'MyRandomCrop' from 'torchvision.transforms' (/home/server2/anaconda3/lib/python3.7/site-packages/torchvision/transforms/__init__.py)

### ISSUE THREAD

**Issue by Zhou-momo** [bearxwm/FLFuse-Net#2]
When I made an error“ImportError: cannot import name 'MyRandomCrop' from 'torchvision.transforms' (/home/server2/anaconda3/lib/python3.7/site-packages/torchvision/transforms/__init__.py)” running test.py, can I ask the author for any solution?

**Comment by bearxwm** [comment]
This is because our previous code modified the code of 'torchvision', which is incompatible with the PyTorch version 1.8 and later. We have fixed this bug and made many other modifications. You can refer to the latest code.

**Comment by Zhou-momo** [comment]
> This is because our previous code modified the code of 'torchvision', which is incompatible with the PyTorch version 1.8 and later. We have fixed this bug and made many other modifications. You can refer to the latest code.

Thank you to the author for your answer.
