### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by robinqwertyuiop** [bearxwm/FLFuse-Net#6]
你好，我想问下这个代码应该如何进行训练呢？我看到NIR数据集里面还有九种类别的数据集。按照正常理解应该是可见光的图片放在一起，红外光的图片放在一起。那像这样的情况训练的时候应该要怎么处理呢

**Comment by bearxwm** [comment]
该脚本已经丢失，但是您可以自行编写图像归类的脚本，来实现‘可见光的图片放在一起，红外光的图片放在一起’，该脚本的实现非常简单。
